name: Cleanup Docker Images

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly, e.g., every Sunday at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cleanup script
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          #!/bin/bash
          # Define the number of most recent tags to keep
          KEEP_TAGS=5

          # Fetch tags from GHCR
          TAGS_RESPONSE=$(curl -s -H "Authorization: Bearer $GHCR_TOKEN" \
          "https://ghcr.io/v2/${REPOSITORY}/tags/list")
          echo "$TAGS_RESPONSE"

          # Check if the response is null or empty
          if [ -z "$TAGS_RESPONSE" ] || [ "$TAGS_RESPONSE" = "null" ]; then
            echo "No tags found or unable to fetch tags."
            exit 0
          fi

          # Parse tags
          TAGS=$(echo "$TAGS_RESPONSE" | jq -r '.tags[]')

          # Sort and skip the most recent $KEEP_TAGS
          DELETE_TAGS=$(echo "$TAGS" | grep -v latest | sort -r | tail -n +$((KEEP_TAGS + 1)))

          # Loop over tags and delete them
          for TAG in $DELETE_TAGS; do
            echo "Deleting tag: $TAG"
            curl -X DELETE -H "Authorization: Bearer $GHCR_TOKEN" \
            "https://ghcr.io/v2/${REPOSITORY}/manifests/$TAG"
          done
