name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change this to the branch you want the action to run on

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Set current date and time as an environment variable
      run: echo "CURRENT_DATE_TIME=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

    - name: Build and push Docker image with Latest Tag
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nmethod/chatgpt-discord-bot:latest

    - name: Build and push Docker image with Date Tag
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          nmethod/chatgpt-discord-bot:latest
          nmethod/chatgpt-discord-bot:${{ env.CURRENT_DATE_TIME }}