name: Vulnerability Scan and Container Build

on:
  schedule:
    - cron: '0 * * * *' # Run Hourly
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trivy_scan_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest image
        run: docker pull ghcr.io/${{ github.repository }}:latest || true

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest
          exit-code: 1
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'


      - name: Set vulnerability flag
        if: ${{ failure() }}
        run: echo "VULNERABILITY_FOUND=true" >> $GITHUB_ENV

      - name: Build and push updated image
        if: github.event_name == 'push' || env.VULNERABILITY_FOUND == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
